hanalum_poll/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("poll/", include('poll.urls', 'poll')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root' : settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root' : settings.STATIC_ROOT}),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

poll/urls.py
from django.urls import path
from .views import (
    show, submit, complete, result
)

app_name = "poll"

urlpatterns = [
    path('<int:poll_id>', show, name="show"),
    path('complete/<int:poll_id>', complete, name="complete"),
    path('result/<int:poll_id>', result, name="result"),
    path('submit/<int:poll_id>', submit, name="submit"),
]

poll/models.py
from django.db import models

class Option(models.Model):
    content = models.CharField(
        verbose_name="내용",
        max_length=1000,
        null=True,
    )

    created_at = models.DateTimeField(
        verbose_name="생성된 날짜",
        auto_now_add=True
    )
    updated_at = models.DateTimeField(
        verbose_name="수정된 날짜",
        auto_now=True
    )

    def __str__(self):
        return self.content


class Poll(models.Model):
    STATUS_CHOICES = (
        ('d', 'draft'),
        ('p', 'published'),
        ('t', 'trash')
    )
    title = models.TextField(
        verbose_name="제목",
        max_length=500,
        null=False,
        default="투표"
    )
    options = models.ManyToManyField(
        Option,
        verbose_name="항목",
    )
    status = models.CharField(
        verbose_name='투표 공개 상태',
        max_length=2,
        default='p',
        null=False,
        choices=STATUS_CHOICES
    )
    created_at = models.DateTimeField(
        verbose_name="생성된 날짜",
        auto_now_add=True
    )
    updated_at = models.DateTimeField(
        verbose_name="수정된 날짜",
        auto_now=True
    )

    def __str__(self):
        return self.title
    

class Vote(models.Model):
    name = models.CharField(
        verbose_name="이름",
        max_length=10,
        null=True,
    )
    poll = models.ForeignKey(
        Poll,
        verbose_name="참가한 투표",
        on_delete=models.DO_NOTHING,
    )
    option = models.ForeignKey(
        Option,
        verbose_name="선택한 항목",
        on_delete=models.DO_NOTHING,
    )
    created_at = models.DateTimeField(
        verbose_name="생성된 날짜",
        auto_now_add=True
    )
    updated_at = models.DateTimeField(
        verbose_name="수정된 날짜",
        auto_now=True
    )

poll/views.py
from django.shortcuts import render, get_object_or_404, redirect

from .models import Poll, Option, Vote

def show(request, poll_id):
    poll = get_object_or_404(Poll, pk=poll_id, status='p')
    response = {
        'poll' : poll,
    }

    return render(request, 'poll/show.dj.html', response)


def submit(request, poll_id):
    poll = get_object_or_404(Poll, pk=poll_id, status='p')
    
    name = request.POST.get('name')
    selected_option_id = request.POST.get('option')
    
    if not name or not selected_option_id:
        return redirect("poll:show", poll_id)

    vote = Vote()
    vote.poll = poll
    vote.name = name
    vote.option = get_object_or_404(Option, pk=selected_option_id)
    vote.save()

    return redirect("poll:complete", poll_id)


def result(request, poll_id):
    poll = get_object_or_404(Poll, pk=poll_id, status='p')
    votes = Vote.objects.filter(poll=poll)
    result = {}

    for option in poll.options.all():
        result[option.content] = []

    for vote in votes:
        result[vote.option.content].append(vote.name)

    print(result)
    response = {
        'poll' : poll,
        'result' : result,
    }

    return render(request, 'poll/result.dj.html', response)


def complete(request, poll_id):
    poll = get_object_or_404(Poll, pk=poll_id, status='p')
    response = {
        'poll' : poll,
    }
    return render(request, 'poll/complete.dj.html', response)

templates/poll/complete.dj.html
{% comment %} 
  poll
{% endcomment %}
{% load bootstrap5 %}
{% load fontawesome_5 %}
{% load static %}
<html>
  <head>
    <title> 한아름 투표 완료 </title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl"
      crossorigin="anonymous">
    <style>
      body {
        margin: 0;
        padding: 0;
        width: 100%;
      }
      main {
        margin: 0;
        padding: 0;
        width: 100%;
        min-height: 1000px;
        height: auto;
      }
    </style>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0"
      crossorigin="anonymous"></script>
  </head>
  <body>
    <main>
      <div class="row h-100 justify-content-center align-items-center">
        <div class = "col-10">
        <div class="card p-3 m-3">
            <div class="card-header text-center">
                <img class="main-icon" src= "{% static 'no-title-logo.png' %}" alt="" width="140" height="140">
                <h2 class="text-center">
                    "{{poll.title}}" 투표를 참가 완료하셨습니다.
                </h2>
            </div>
            <div class="card-content text-center">
                <a href="{% url 'poll:result' poll.id %}"> 투표 결과 확인하러 가기 </a>
            </div>
        </div>
      </div>
    </main>


  </body>
</html>

templates/poll/result.dj.html
{% comment %} 
  poll, result
{% endcomment %}
{% load bootstrap5 %}
{% load fontawesome_5 %}
{% load static %}
<html>
  <head>
    <title> 한아름 투표 완료 </title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl"
      crossorigin="anonymous">
    <style>
      body {
        margin: 0;
        padding: 0;
        width: 100%;
      }
      main {
        margin: 0;
        padding: 0;
        width: 100%;
        min-height: 1000px;
        height: auto;
      }
    </style>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0"
      crossorigin="anonymous"></script>
  </head>
  <body>
    <main>
      <div class="row h-100 justify-content-center align-items-center">
        <div class = "col-10">
        <div class="card p-3 m-3">
            <div class="card-header text-center">
                <img class="main-icon" src= "{% static 'no-title-logo.png' %}" alt="" width="140" height="140">
                <h2 class="text-center">
                    "{{poll.title}}" 투표 결과
                </h2>
            </div>
            <div class="card-content p-3">
                {% for key, values in result.items %}
                    <h3> {{key}}</h3>
                    <div class="p-2">
                        (총 {{ values|length }} 명)
                        {% for name in values %}
                            {{name}},
                        {% endfor %}
                    </div>
                {% endfor%}

            </div>
            <div class="card-footer text-center">
                <a href="{% url 'poll:result' poll.id %}"> 투표 결과 갱신하기 </a>
            </div>
        </div>
      </div>
    </main>
  </body>
</html>

templates/poll/show.dj.html
{% comment %} 
  poll
{% endcomment %}
{% load bootstrap5 %}
{% load fontawesome_5 %}
{% load static %}
<html>
  <head>
    <title> 한아름 투표 </title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl"
      crossorigin="anonymous">
    <style>
      body {
        margin: 0;
        padding: 0;
        width: 100%;
      }
      main {
        margin: 0;
        padding: 0;
        width: 100%;
        min-height: 1000px;
        height: auto;
      }
    </style>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0"
      crossorigin="anonymous"></script>
  </head>
  <body>
    <main>
      <div class="row h-100 justify-content-center align-items-center">
        <div class = "col-10">
          <form action="{% url 'poll:submit' poll.id %}" method="POST">
            {% csrf_token %}
            <div class="card p-3 m-3">
              <div class="card-header text-center">
                <img class="main-icon" src= "{% static 'no-title-logo.png' %}" alt="" width="140" height="140">
                <h2 class="text-center">
                  {{ poll.title }}
                </h2>
              </div>
              <div class="card-content p-3">
                <div class="m-3">
                  <label for="nameInput" class="form-label">본명을 제대로 입력해주세요.</label>
                  <input class="form-control" id="nameInput" placeholder="홍길동" name="name">
                </div>
                <div class="option-groups p-3">
                  {% for option in poll.options.all %}
                    <div class="form-check">
                      <input class="form-check-input" type="radio" id="option-{{option.id}}" name="option" value="{{option.id}}">
                      <label class="form-check-label" for="option-{{option.id}}">
                        {{ option.content }}
                      </label>
                    </div>
                  {% endfor %}
                </div>
              </div>
              <div class="card-footer text-center p-1">
                <button type="submit" class="btn btn-primary m-1"> 제출 </button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </main>


  </body>
</html>